const songs = [
    { position: 1, flag: "🇦🇱", country: "Albanien", artist: "Shkodra Elektronike", title: "Zjerm" },
    { position: 2, flag: "🇦🇲", country: "Armenien", artist: "Parg", title: "Survivor" },
    { position: 3, flag: "🇦🇺", country: "Australien", artist: "Go-Jo", title: "Milkshake Man" },
    { position: 4, flag: "🇦🇹", country: "Österreich", artist: "JJ", title: "Wasted Love" },
    { position: 5, flag: "🇦🇿", country: "Aserbaidschan", artist: "Mamagama", title: "Run with U" },
    { position: 6, flag: "🇧🇪", country: "Belgien", artist: "Red Sebastian", title: "Strobe Lights" },
    { position: 7, flag: "🇭🇷", country: "Kroatien", artist: "Marko Bošnjak", title: "Poison Cake" },
    { position: 8, flag: "🇨🇾", country: "Zypern", artist: "Theo Evan", title: "Shh" },
    { position: 9, flag: "🇨🇿", country: "Tschechien", artist: "Adonxs", title: "Kiss Kiss Goodbye" },
    { position: 10, flag: "🇩🇰", country: "Dänemark", artist: "Sissal", title: "Hallucination" },
    { position: 11, flag: "🇪🇪", country: "Estland", artist: "Tommy Cash", title: "Espresso Macchiato" },
    { position: 12, flag: "🇫🇮", country: "Finnland", artist: "Erika Vikman", title: "Ich komme" },
    { position: 13, flag: "🇫🇷", country: "Frankreich", artist: "Louane", title: "Maman" },
    { position: 14, flag: "🇬🇪", country: "Georgien", artist: "Mariam Shengelia", title: "Freedom" },
    { position: 15, flag: "🇩🇪", country: "Deutschland", artist: "Abor & Tynna", title: "Baller" },
    { position: 16, flag: "🇬🇷", country: "Griechenland", artist: "Klavdia", title: "Asteromata" },
    { position: 17, flag: "🇮🇸", country: "Island", artist: "Væb", title: "Róa" },
    { position: 18, flag: "🇮🇪", country: "Irland", artist: "Emmy", title: "Laika Party" },
    { position: 19, flag: "🇮🇱", country: "Israel", artist: "Yuval Raphael", title: "New Day Will Rise" },
    { position: 20, flag: "🇮🇹", country: "Italien", artist: "Lucio Corsi", title: "Volevo essere un duro" },
    { position: 21, flag: "🇱🇻", country: "Lettland", artist: "Tautumeitas", title: "Bur man laimi" },
    { position: 22, flag: "🇱🇹", country: "Litauen", artist: "Katarsis", title: "Tavo akys" },
    { position: 23, flag: "🇱🇺", country: "Luxemburg", artist: "Laura Thorn", title: "La Poupée monte le son" },
    { position: 24, flag: "🇲🇹", country: "Malta", artist: "Miriana Conte", title: "Serving" },
    { position: 25, flag: "🇲🇪", country: "Montenegro", artist: "Nina Žižić", title: "Dobrodošli" },
    { position: 26, flag: "🇳🇱", country: "Niederlande", artist: "Claude", title: "C'est la vie" },
    { position: 27, flag: "🇳🇴", country: "Norwegen", artist: "Kyle Alessandro", title: "Lighter" },
    { position: 28, flag: "🇵🇱", country: "Polen", artist: "Justyna Steczkowska", title: "Gaja" },
    { position: 29, flag: "🇵🇹", country: "Portugal", artist: "Napa", title: "Deslocado" },
    { position: 30, flag: "🇸🇲", country: "San Marino", artist: "Gabry Ponte", title: "Tutta l'Italia" },
    { position: 31, flag: "🇷🇸", country: "Serbien", artist: "Princ", title: "Mila" },
    { position: 32, flag: "🇸🇮", country: "Slowenien", artist: "Klemen", title: "How Much Time Do We Have Left" },
    { position: 33, flag: "🇪🇸", country: "Spanien", artist: "Melody", title: "Esa diva" },
    { position: 34, flag: "🇸🇪", country: "Schweden", artist: "KAJ", title: "Bara bada bastu" },
    { position: 35, flag: "🇨🇭", country: "Schweiz", artist: "Zoë Më", title: "Voyage" },
    { position: 36, flag: "🇺🇦", country: "Ukraine", artist: "Ziferblat", title: "Bird of Pray" },
    { position: 37, flag: "🇬🇧", country: "Vereinigtes Königreich", artist: "Remember Monday", title: "What the Hell Just Happened?" }
  ];
  
  export default songs;
  