const songs = [
    { position: 1, flag: "🇦🇱", country: "Albanien", artist: "Shkodra Elektronike", title: "Zjerm", tags: ["🔥", "❤️ - 1", "🚀 - 10"] },
    { position: 2, flag: "🇦🇲", country: "Armenien", artist: "Parg", title: "Survivor", tags: ["🤷‍♂️"] },
    { position: 3, flag: "🇦🇺", country: "Australien", artist: "Go-Jo", title: "Milkshake Man", tags: ["👍", "🎉"] },
    { position: 4, flag: "🇦🇹", country: "Österreich", artist: "JJ", title: "Wasted Love", tags: ["🔥", "👍", "🚀 - 2"] },
    { position: 5, flag: "🇦🇿", country: "Aserbaidschan", artist: "Mamagama", title: "Run with U", tags: ["🤷‍♂️"] },
    { position: 6, flag: "🇧🇪", country: "Belgien", artist: "Red Sebastian", title: "Strobe Lights", tags: ["🔥", "🎉","👍", "🚀 - 8"] },
    { position: 7, flag: "🇭🇷", country: "Kroatien", artist: "Marko Bošnjak", title: "Poison Cake", tags: ["👎"] },
    { position: 8, flag: "🇨🇾", country: "Zypern", artist: "Theo Evan", title: "Shh", tags: ["🤷‍♂️"] },
    { position: 9, flag: "🇨🇿", country: "Tschechien", artist: "Adonxs", title: "Kiss Kiss Goodbye", tags: ["🔥", "👍", "🚀 - 6"] },
    { position: 10, flag: "🇩🇰", country: "Dänemark", artist: "Sissal", title: "Hallucination", tags: ["👎"] },
    { position: 11, flag: "🇪🇪", country: "Estland", artist: "Tommy Cash", title: "Espresso Macchiato", tags: ["👍", "🎉", "🚀 - 9"] },
    { position: 12, flag: "🇫🇮", country: "Finnland", artist: "Erika Vikman", title: "Ich komme", tags: ["🔥","❤️ - 2", "🎉", "🚀 - 7"] },
    { position: 13, flag: "🇫🇷", country: "Frankreich", artist: "Louane", title: "Maman", tags: ["🤷‍♂️", "🚀 - 3"] },
    { position: 14, flag: "🇬🇪", country: "Georgien", artist: "Mariam Shengelia", title: "Freedom", tags: ["💤"] },
    { position: 15, flag: "🇩🇪", country: "Deutschland", artist: "Abor & Tynna", title: "Baller", tags: ["❤️ - 3", "🎉"] },
    { position: 16, flag: "🇬🇷", country: "Griechenland", artist: "Klavdia", title: "Asteromata", tags: ["❤️ - 8", "😢"] },
    { position: 17, flag: "🇮🇸", country: "Island", artist: "Væb", title: "Róa", tags: ["👍", "🎉"] },
    { position: 18, flag: "🇮🇪", country: "Irland", artist: "Emmy", title: "Laika Party", tags: ["👍", "🎉"] },
    { position: 19, flag: "🇮🇱", country: "Israel", artist: "Yuval Raphael", title: "New Day Will Rise", tags: ["🤷‍♂️", "🚀 - 5"] },
    { position: 20, flag: "🇮🇹", country: "Italien", artist: "Lucio Corsi", title: "Volevo essere un duro", tags: ["👍"] },
    { position: 21, flag: "🇱🇻", country: "Lettland", artist: "Tautumeitas", title: "Bur man laimi", tags: ["👍"] },
    { position: 22, flag: "🇱🇹", country: "Litauen", artist: "Katarsis", title: "Tavo akys", tags: ["👎"] },
    { position: 23, flag: "🇱🇺", country: "Luxemburg", artist: "Laura Thorn", title: "La Poupée monte le son", tags: ["👍"] },
    { position: 24, flag: "🇲🇹", country: "Malta", artist: "Miriana Conte", title: "Serving", tags: ["❤️ - 5", "🎉"] },
    { position: 25, flag: "🇲🇪", country: "Montenegro", artist: "Nina Žižić", title: "Dobrodošli", tags: ["🤷‍♂️"] },
    { position: 26, flag: "🇳🇱", country: "Niederlande", artist: "Claude", title: "C'est la vie", tags: ["❤️ - 7", "🔥", "🎉", "🚀 - 4"] },
    { position: 27, flag: "🇳🇴", country: "Norwegen", artist: "Kyle Alessandro", title: "Lighter", tags: ["👍", "🎉"] },
    { position: 28, flag: "🇵🇱", country: "Polen", artist: "Justyna Steczkowska", title: "Gaja", tags: ["❤️ - 6"] },
    { position: 29, flag: "🇵🇹", country: "Portugal", artist: "Napa", title: "Deslocado", tags: ["👍"] },
    { position: 30, flag: "🇸🇲", country: "San Marino", artist: "Gabry Ponte", title: "Tutta l'Italia", tags: ["👍", "🎉"] },
    { position: 31, flag: "🇷🇸", country: "Serbien", artist: "Princ", title: "Mila", tags: ["💤"] },
    { position: 32, flag: "🇸🇮", country: "Slowenien", artist: "Klemen", title: "How Much Time Do We Have Left", tags: ["💤", "😢"] },
    { position: 33, flag: "🇪🇸", country: "Spanien", artist: "Melody", title: "Esa diva", tags: ["👎", "🎉"] },
    { position: 34, flag: "🇸🇪", country: "Schweden", artist: "KAJ", title: "Bara bada bastu", tags: ["❤️ - 4", "🔥", "🎉", "🚀 - 1"] },
    { position: 35, flag: "🇨🇭", country: "Schweiz", artist: "Zoë Më", title: "Voyage", tags: ["👍"] },
    { position: 36, flag: "🇺🇦", country: "Ukraine", artist: "Ziferblat", title: "Bird of Pray", tags: ["👍"] },
    { position: 37, flag: "🇬🇧", country: "Vereinigtes Königreich", artist: "Remember Monday", title: "What the Hell Just Happened?", tags: ["👍", "🎉"] }
  ];
  
  export default songs;
  